services:
  web:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: >
      sh -c "
        bundle install &&
        rails db:create db:migrate &&
        rails server -b 0.0.0.0 -e development
      "

volumes:
  bundle_cache: 