
services:
  web:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:/app/db/development.sqlite3
    depends_on:
      - db
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]    
    # command: rails db:setup

  db:
    image: alpine:latest
    volumes:
      - sqlite_data:/app/db
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"

volumes:
  bundle_cache:
  sqlite_data: 