

services:
  web:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - ./db:/app/db
      - ./tmp:/app/tmp
      - ./log:/app/log
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      # - RAILS_LOG_TO_STDOUT=true
      - CRYPTO_UPDATE_INTERVAL=300
    working_dir: /app
    command: bundle exec rails server -b 0.0.0.0 -e development
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  bundle_cache:
  redis_data: 